<a href="https://colab.research.google.com/github/KristinePenaroyo/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Laboratory 2 : Matrices

Now that we have a fundamental knowledge about Python, we'll try to look into greater dimensions.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

# Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have $A$ and $B$ as system of equation.

$$
A = \left\{
    \begin{array}\
        t + u \\ 
        9t - 3u
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        t+u+v \\ 
        5t -7u -v \\
        -2t + 3u +6v
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        t-9u+2v-5w \\
        t-4u-6v+w \\
        3t-u+2v-5w \\
    \end{array}
\right. \\
$$

We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 9 & 9 \\ 5 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 9 & 9 & 9 \\ 3 & -6 & -9 \\ -6 & 4 & 6\end{bmatrix}\\
C=\begin{bmatrix} 9 & -6 & 7 & -5 \\ 7 & -9 & -6 & 9 \\ 6 & -9 & 3 & -6\end{bmatrix}\\
$$

So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

### Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.<br>
Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using <b>shape</b>, <b>dimensions</b> and <b>size</b> attributes, we'll use them to analyze these matrices.

In [8]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [10]:
## Declearing a 2 x 2 matrix 
K = np.array([
    [6,4],
    [2,8]          
])
describe_mat(K)

Matrix:
[[6 4]
 [2 8]]

Shape:	(2, 2)
Rank:	2



In [12]:
R = np.array([
    [4,2,1],
    [1,3,7]
])
describe_mat(R)

Matrix:
[[4 2 1]
 [1 3 7]]

Shape:	(2, 3)
Rank:	2



In [14]:
## Declearing a 3 x 2 matrix
I = np.array([
    [10, 2],
    [5, 7],
    [20, 19]
])
describe_mat(I)

Matrix:
[[10  2]
 [ 5  7]
 [20 19]]

Shape:	(3, 2)
Rank:	2



In [17]:
S = np.array([13,8,3,4,87,5,2])
describe_mat(S)

Matrix:
[13  8  3  4 87  5  2]

Shape:	(7,)
Rank:	1



## Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their <b>shape</b> and another is according to their <b>element values</b>. We'll try to go through them.

### According to shape

#### Row and Column Matrices

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [26]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    8, 7, 4, -6
]) ## this is a 1-D Matrix with a shape of (4,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [8,7,4,-6]
]) ## this is a 2-D Matrix with a shape of (8,4)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[ 8  7  4 -6]

Shape:	(4,)
Rank:	1

Matrix:
[[ 8  7  4 -6]]

Shape:	(1, 4)
Rank:	2



In [27]:
## Declaring a Column Matrix

col_mat = np.array([
    [2],
    [3],
    [-78],
    [43],
    [7]
]) ## this is a 2-D Matrix with a shape of (5,1)
describe_mat(col_mat)

Matrix:
[[  2]
 [  3]
 [-78]
 [ 43]
 [  7]]

Shape:	(5, 1)
Rank:	2



#### Square Matrices

Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if $i = j$. We can tweak our matrix descriptor function to determine square matrices.

In [28]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [30]:
square_mat = np.array([
    [8,7,-5],
    [2,13,9],
    [3,4,1],
    [6,-9,8]
])

non_square_mat = np.array([
    [8,12,6,-19],
    [2,-5,6,76]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[ 8  7 -5]
 [ 2 13  9]
 [ 3  4  1]
 [ 6 -9  8]]

Shape:	(4, 3)
Rank:	2
Is Square: False

Matrix:
[[  8  12   6 -19]
 [  2  -5   6  76]]

Shape:	(2, 4)
Rank:	2
Is Square: False



### According to element values

#### Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [31]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [32]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


#### Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [43]:
zero_mat_row = np.zeros((4,9))
zero_mat_sqr = np.zeros((9,9))
zero_mat_rct = np.zeros((6,9))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [41]:
ones_mat_row = np.ones((6,4))
ones_mat_sqr = np.ones((4,4))
ones_mat_rct = np.ones((9,4))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix. 

In [46]:
np.array([
    [8,0,0],
    [0,9,0],
    [0,0,10]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[ 8,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 10]])

In [48]:
d = np.diag([24,38,47,88,95])
#d.shape[0] == d.shape[1]
d

array([[24,  0,  0,  0,  0],
       [ 0, 38,  0,  0,  0],
       [ 0,  0, 47,  0,  0],
       [ 0,  0,  0, 88,  0],
       [ 0,  0,  0,  0, 95]])

#### Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [50]:
np.eye(20)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [52]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### Upper Triangular Matrix

An upper triangular matrix is a matrix that has no values below the diagonal.


In [54]:
np.array([
    [8,-72,12],
    [6,9,20],
    [-5,4,2]
])

array([[  8, -72,  12],
       [  6,   9,  20],
       [ -5,   4,   2]])

In [57]:
V = np.array([
              [9, -10, 5, 27, -2],
              [9, -10, 5, 27, -2],
              [9, -10, 5, 27, -2],
              [9, -10, 5, 27, -2],
              [9, -10, 5, 27, -2],
])
np.triu(V)


array([[  9, -10,   5,  27,  -2],
       [  0, -10,   5,  27,  -2],
       [  0,   0,   5,  27,  -2],
       [  0,   0,   0,  27,  -2],
       [  0,   0,   0,   0,  -2]])

#### Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [59]:
np.tril(V)


array([[  9,   0,   0,   0,   0],
       [  9, -10,   0,   0,   0],
       [  9, -10,   5,   0,   0],
       [  9, -10,   5,  27,   0],
       [  9, -10,   5,  27,  -2]])

In [61]:
np.array([
          [3,0,0],
          [9,13,0],
          [1,17,23]
])

array([[ 3,  0,  0],
       [ 9, 13,  0],
       [ 1, 17, 23]])

##Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$


$$\theta =\begin{bmatrix} 5 & 3 & -1\end{bmatrix}\\ $$

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


In [62]:
A = np.array([
    [1, 2, 1],
    [0, 4, -1],
    [0, 0, 10]
])
A

array([[ 1,  2,  1],
       [ 0,  4, -1],
       [ 0,  0, 10]])

3. Given the matrix below, express it as a linear combination in a markdown.

In [63]:
G = np.array([ 
    [1,7,8], 
    [2,2,2], 
    [4,6,7] 
])

$$
G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix}\\
$$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [65]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
H = \begin{bmatrix} 
1 & 0 & 0 \\
2 & 2 & 0\\
4 & 6 & 7 \\
\end{bmatrix}
$$

$$
H = \left\{\begin{array}
1x \\
2x + 2y\\
4x + 6y + 7z
\end{array}\right.
$$

##Matrix Algebra

###Addition

In [81]:
A = np.array([
    [9,4],
    [7,10],
    [-2,6]
])
B = np.array([
    [5,17],
    [-4,5],
    [3,11]
])
A+B

array([[14, 21],
       [ 3, 15],
       [ 1, 17]])

In [70]:
3+B ##Broadcasting
# 2*np.ones(A.shape)+A

array([[ 8, 20],
       [-1,  8],
       [ 6, 14]])

### Subtraction

In [71]:
A-B

array([[  4, -13],
       [ 11,   5],
       [ -5,  -5]])

In [75]:
5-B == 5*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

###Element-wise Multiplication


In [76]:
A*B

array([[ 45,  68],
       [-28,  50],
       [ -6,  66]])

In [78]:
4*A

array([[36, 16],
       [28, 40],
       [-8, 24]])

In [83]:
A @ B

ValueError: ignored

In [85]:
alpha=5**-5
A/(alpha+B)

array([[ 1.79988481,  0.23528969],
       [-1.75014001,  1.99987201],
       [-0.66659556,  0.54543868]])

In [86]:
np.add(A,B)

array([[14, 21],
       [ 3, 15],
       [ 1, 17]])

##**Activity**

### Task 1

Create a function named mat_desc() that througouhly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.
2. Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than  (3,3) . In your 
methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [87]:
## Function area

In [ ]:
## Matrix declarations

In [ ]:
## Test Areas

### Task 2

Create a function named mat_operations() that takes in two matrices a input parameters it should:


1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the differen of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

## Conclusion


For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "How can matrix operations solve problems in technology?".